//POKEDEX
export const SET_POKEMON = "SET_POKEMON";
export const SET_LOADING_POKEMON = "SET_LOADING_POKEMON";
//POKESHOP
export const SET_SHOP_ITEMS = "SET_SHOP_ITEMS";
export const SET_SHOP_LOADING = "SET_SHOP_LOADING";
//POKEPACK
export const BUY_ITEM = "BUY_ITEM";
